# Generated by Django 5.1.4 on 2026-02-05 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEBET_ORDER', 'Начисление за заказ (Долг)'), ('KREDIT_PAYMENT', 'Оплата (Погашение долга)'), ('CORRECTION', 'Корректировка баланса')], max_length=20, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/%d/', verbose_name='Фото чека')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждена (ручной чек) / Проведена (О!Деньги)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий/ID транзакции О!Деньги')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['created_at'],
            },
        ),
    ]
