# Generated by Django 5.1.4 on 2026-02-12 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0002_initial'),
        ('app_orders', '0003_alter_order_employee_alter_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Payment ID')),
                ('screenshot', models.ImageField(upload_to='payments/', verbose_name='Скриншот оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app_orders.order', verbose_name='Принадлежит заказу')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
