# Generated by Django 5.1.4 on 2026-02-13 05:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_departments(apps, schema_editor):
    Department = apps.get_model("app_users", "Department")
    departments = [
        "Департамент цифровой трансформации и инноваций",
        "Департамент стратегического планирования и аналитики",
        "Департамент по работе с обращениями",
        "Департамент финансового планирования и учета",
        "Административный департамент",
        "ГП ЦЕО Руководство",
        "Департамент юридической и социальной экспертизы",
        "Другое",
    ]
    for name in departments:
        Department.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_user_id_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='app_users.department', verbose_name='Департамент'),
        ),
        migrations.RunPython(seed_departments, migrations.RunPython.noop),
    ]
