# Generated by Django 5.1.4 on 2026-02-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_remove_user_birth_year_user_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='SingleLunch', max_length=100, verbose_name='Название проекта')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Логотип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
            options={
                'verbose_name': 'Брендинг',
                'verbose_name_plural': 'Брендинг',
                'db_table': 'branding_settings',
            },
        ),
    ]
