# Generated by Codex on 2026-02-14

from django.db import migrations


def add_other_department(apps, schema_editor):
    Department = apps.get_model("app_users", "Department")
    Department.objects.get_or_create(name="Другое")


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0005_brandingsettings"),
    ]

    operations = [
        migrations.RunPython(add_other_department, migrations.RunPython.noop),
    ]
