# Generated by Django 5.1.4 on 2026-02-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_seed_department_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='branding/payment_qr/', verbose_name='Единый QR оплаты'),
        ),
    ]
