# Generated by Django 5.1.4 on 2026-02-23 03:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0007_brandingsettings_payment_qr"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandingsettings",
            name="lunch_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("170.00"),
                max_digits=6,
                verbose_name="Цена за порцию (сом)",
            ),
        ),
    ]
