# Generated by Django 5.1.4 on 2026-02-05 13:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата обеда')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно для выбора')),
                ('selection_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок выбора (напр. 20:00 предыдущего дня)')),
            ],
            options={
                'verbose_name': 'Дневное меню',
                'verbose_name_plural': 'Дневные меню',
            },
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название позиции')),
                ('description', models.TextField(verbose_name='Состав')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('170.0'), max_digits=6, verbose_name='Цена')),
                ('daily_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app_catering.dailymenu', verbose_name='Принадлежит меню дня')),
            ],
            options={
                'verbose_name': 'Вариант меню',
                'verbose_name_plural': 'Варианты меню',
            },
        ),
    ]
