# Generated by Django 5.1.4 on 2026-02-12 17:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catering', '0002_alter_dailymenu_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenu',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создатель меню'),
        ),
        migrations.AddField(
            model_name='menuoption',
            name='category',
            field=models.CharField(choices=[('MAIN', 'Основное'), ('SOUP', 'Суп'), ('SALAD', 'Салат')], default='MAIN', max_length=10, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='date',
            field=models.DateField(unique=True, verbose_name='Дата обеда'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Daily Menu ID'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='selection_deadline',
            field=models.DateTimeField(verbose_name='Крайний срок выбора (напр. 20:00 предыдущего дня)'),
        ),
        migrations.AlterField(
            model_name='menuoption',
            name='daily_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app_catering.dailymenu', verbose_name='Принадлежит меню дня'),
        ),
        migrations.AlterField(
            model_name='menuoption',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Menu Option ID'),
        ),
    ]
