# Generated by Django 5.1.4 on 2026-02-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catering', '0003_dailymenu_created_by_menuoption_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenu',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='menu_qr/', verbose_name='QR для оплаты'),
        ),
    ]
