# Generated by Django 5.1.4 on 2026-02-16 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_catering', '0004_dailymenu_payment_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuoption',
            name='category',
        ),
    ]
