# Generated by Django 5.1.4 on 2026-02-16 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_catering', '0005_remove_menuoption_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuoption',
            name='description',
        ),
    ]
