# Generated by Django 5.1.4 on 2026-02-16 06:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catering', '0006_remove_menuoption_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Duty Assignment ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата дежурства')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duty_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Дежурный')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_duty_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
            ],
            options={
                'verbose_name': 'Дежурство',
                'verbose_name_plural': 'Дежурства',
                'ordering': ['date'],
            },
        ),
    ]
