# Generated by Django 5.1.4 on 2026-02-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_catering', '0007_dutyassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymenu',
            name='is_active',
        ),
    ]
