# Generated by Django 5.1.4 on 2026-02-05 13:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_catering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество порций')),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена за 1 порцию на момент заказа')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Новый заказ (выбран)'), ('AWAITING_PAYMENT', 'Ожидает оплаты'), ('PAID', 'Оплачен (подтвержден)'), ('CANCELLED', 'Отменен'), ('MISSED_DEADLINE', 'Пропущен срок')], default='NEW', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Итоговая сумма заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='app_catering.dailymenu', verbose_name='Меню дня')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
