# Generated by Django 5.1.4 on 2026-02-13 04:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0003_alter_order_employee_alter_order_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_date', models.DateField(verbose_name='Дата меню')),
                ('channel', models.CharField(choices=[('TELEGRAM', 'Telegram'), ('MATTERMOST', 'Mattermost')], max_length=20, verbose_name='Канал')),
                ('notification_type', models.CharField(choices=[('ORDER_REMINDER', 'Напоминание о заказе')], default='ORDER_REMINDER', max_length=30, verbose_name='Тип уведомления')),
                ('status', models.CharField(choices=[('SENT', 'Отправлено'), ('FAILED', 'Ошибка')], max_length=10, verbose_name='Статус отправки')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог уведомления',
                'verbose_name_plural': 'Логи уведомлений',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'menu_date', 'channel', 'notification_type'), name='uniq_notification_per_user_menu_channel_type')],
            },
        ),
    ]
