# Generated by Django 5.1.4 on 2026-02-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0004_notificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('ORDER_REMINDER', 'Напоминание о заказе'), ('DUTY_REMINDER', 'Напоминание о дежурстве')], default='ORDER_REMINDER', max_length=30, verbose_name='Тип уведомления'),
        ),
    ]
