# Generated by Django 5.1.4 on 2026-02-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0005_alter_notificationlog_notification_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
    ]
